routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('/categories', 'CategoryController');
Route::resource('/products', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';

    protected $fillable = [
        'title',
        'categoryId',
        'title',
        'description',
        'image',
        'stock',
        'price',
        'isActive'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'categoryId');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('product.create',  compact('categories'));
    }//

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        $this->validate(\request(),
            [
                'title' => 'required',
                'categoryId' => 'required',
                'description' => 'required',
                'stock' => 'required',
                'price' => 'required',
            ]
        );

        $product = Product::create([
            'title' => \request('title'),
            'categoryId' => \request('categoryId'),
            'description' => \request('description'),
            'stock' => \request('stock'),
            'price' => \request('price'),
            'isActive' => \request('isActive') ? true : false,
        ]);

        if ($product) {
            $image = Storage::disk('public')->put('/', \request()->file('image'));
            //Storage::disk('sftp')->put('/', \request()->file('image'));
            $product->image = $image;
            $product->save();
        }

        return redirect()->back()->with('message', $product->title . ' başarıyla eklendi.');

    }

    /**
     * Display the specified resource.
     *
     * @param  Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/api/ProductController.php
<?php

namespace App\Http\Controllers\api;

use App\Category;
use App\Http\Resources\CategoryResource;
use App\Http\Resources\ProductResource;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function index($id)
    {
        $category = Category::find($id);
        if ($category) {
            return response()->json([
                'status' => 'success',
                'data' =>  new CategoryResource($category)
            ]);
        } else {
            return response()->json([
                'status' => 'warning',
                'data' => 'Category not found.'
            ]);
        }
    }

    public function show($id)
    {
        $product = Product::find($id);
        if ($product) {
            return response()->json([
                'status' => 'success',
                'data' =>  new ProductResource($product)
            ]);
        } else {
            return response()->json([
                'status' => 'warning',
                'data' => 'Product not found.'
            ]);
        }

    }

}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')

    @if(session()->has('message'))
        <div class="alert alert-success" role="alert">
            {{ session()->get('message') }}
        </div>
    @endif

    <h4>Ürün Ekle</h4>
    <hr />
    <form method="post" action="{{ route('products.store') }}" enctype="multipart/form-data">
        @csrf

        <div class="form-group">
            <label for="title">Ürün Adı</label>
            <input type="text" class="form-control" id="title" name="title" aria-describedby="titleHelp" placeholder="Ürün Adı">
            @if($errors->has('title'))
                <small id="titleHelp" class="form-text text-muted text-danger">{{ $errors->first('title') }}</small>
            @endif
        </div>

        <div class="form-group">
            <label for="image">Fotoğraf</label>
            <input type="file" class="form-control" id="image" name="image" aria-describedby="imageHelp" />
            @if($errors->has('image'))
                <small id="imageHelp" class="form-text text-muted text-danger">{{ $errors->first('image') }}</small>
            @endif
        </div>

        <div class="form-group">
            <label for="categoryId">Kategori</label>
            <select class="form-control" id="categoryId" name="categoryId">
                <option value="0">Seçiniz..</option>
                @foreach($categories as $item)
                    <option value="{{ $item->id }}">{{ $item->title }}</option>
                @endforeach
            </select>
            @if($errors->has('categoryId'))
                <small id="parentIdHelp" class="form-text text-muted">{{ $errors->first('categoryId') }}</small>
            @endif
        </div>

        <div class="form-group">
            <label for="description">Ürün Açıklaması</label>
            <textarea class="form-control" id="description" name="description" aria-describedby="descriptionHelp" placeholder="Ürün Açıklaması"></textarea>
            @if($errors->has('description'))
                <small id="descriptionHelp" class="form-text text-muted">{{ $errors->first('description') }}</small>
            @endif
        </div>

        <div class="form-group">
            <label for="stock">Stok</label>
            <input type="number" class="form-control" id="stock" name="stock" aria-describedby="stockHelp" placeholder="Stok adedi">
            @if($errors->has('stock'))
                <small id="stockHelp" class="form-text text-muted">{{ $errors->first('stock') }}</small>
            @endif
        </div>

        <div class="form-group">
            <label for="stock">Fiyat</label>
            <input type="number" class="form-control" id="price" name="price" aria-describedby="priceHelp" placeholder="Fiyat">
            @if($errors->has('price'))
                <small id="priceHelp" class="form-text text-muted">{{ $errors->first('price') }}</small>
            @endif
        </div>

        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="isActive" name="isActive">
            <label class="form-check-label" for="isActive">Aktif</label>
        </div>

        <button type="submit" class="btn btn-primary">Kaydet</button>
    </form>

@endsection

resources/views/product/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ozgur
 * Date: 12.01.2019
 * Time: 22:42
 */

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')

    <h4>Ürün Lisesi</h4>
    <hr />
    <a href="{{ route('products.create') }}">Yeni Ekle</a>

    <table class="table table-bordered">
        <thead>
            <th>#</th>
            <th>Ürün Adı</th>
            <th>Kategori Adı</th>
            <th>Resim</th>
        </thead>
        <tbody>
        @foreach($products as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->title }}</td>
                <td>{{ $item->category->title }}</td>
                <td><img src="{{ 'http://api.kozayayin.app-xr.com/media/' . $item->image }}" /></td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection

resources/views/product/show.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ozgur
 * Date: 12.01.2019
 * Time: 22:42
 */