routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('/categories', 'CategoryController');
Route::resource('/products', 'ProductController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';

    protected $fillable = [
        'title',
        'parentId',
        'image',
    ];

    public function children()
    {
        return $this->hasMany(Category::class, 'parentId');
    }

    public function products()
    {
        return $this->hasMany(Product::class, 'categoryId');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('category.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        $this->validate(\request(),
            [
               'title' => 'required',
               'parentId' => 'required'
            ]);

        $category = Category::create([
            'title' => \request('title'),
            'parentId' => \request('parentId'),
            'image' => ''
        ]);

        return redirect()->back()->with('message', $category->title . ' başarıyla eklendi.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $category
     * @return \Illuminate\Http\Response
     */
    public function show($category)
    {
        return view('category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($category)
    {
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/api/CategoryController.php
<?php

namespace App\Http\Controllers\api;

use App\Category;
use App\Http\Resources\CategoryResource;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::where('parentId', 0)->get();
        return response()->json([
            'status' => 'success',
            'data' => CategoryResource::collection($categories)
        ]);
    }

    public function children($id)
    {
        $category = Category::find($id);
        if ($category) {
            return response()->json([
                'status' => 'success',
                'data' => $category->children
            ]);
        } else {
            return response()->json([
                'status' => 'warning',
                'data' => 'Category not found.'
            ]);
        }
    }

}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')

    @if(session()->has('message'))
        <div class="alert alert-success" role="alert">
            {{ session()->get('message') }}
        </div>
    @endif

    <h4>Kategori Ekle</h4>
    <hr />
    <form method="post" action="{{ route('categories.store') }}">
        @csrf
        <div class="form-group">
            <label for="title">Kategori Adı</label>
            <input type="text" class="form-control" id="title" name="title" aria-describedby="titleHelp" placeholder="Kategori Adı">
            <small id="titleHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="parentId">Üst Kategori</label>
            <select class="form-control" id="parentId" name="parentId">
                <option value="0">Seçiniz..</option>
                @foreach($categories as $item)
                    <option value="{{ $item->id }}">{{ $item->title }}</option>
                @endforeach
            </select>
            <small id="parentIdHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </form>

@endsection

resources/views/category/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ozgur
 * Date: 12.01.2019
 * Time: 22:42
 */

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')

    <h4>Kategori Lisesi</h4>
    <hr />
    <a href="{{ route('categories.create') }}">Yeni Ekle</a>

    <table class="table table-bordered">
        <thead>
            <th>#</th>
            <th>Kategori Adı</th>
            <th>Resim</th>
        </thead>
        <tbody>
            @foreach($categories as $item)
                <tr>
                    <td>{{ $item->id }}</td>
                    <td>{{ $item->title }}</td>
                    <td>{{ $item->image }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

@endsection

resources/views/category/show.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: ozgur
 * Date: 12.01.2019
 * Time: 22:42
 */